import { StyleSheet } from "react-native";
import { colors, sizes } from "../Theme/index";

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  map: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  marker: { position: "absolute" },
  centerContainer: {
    position: "absolute",
    top: 15,
    alignSelf: "center",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: 10,
    paddingLeft: sizes.sm,
    width: 350,
    height: sizes.lg,
    borderRadius: sizes.xl,
    backgroundColor: colors.white,
    opacity: 0.8,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
  },
  center: {
    fontSize: sizes.xs,
    color: colors.main,
  },
  profile: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#e198f9",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
  },
  initial: {
    color: "#5e006b",
    fontSize: sizes.xs,
    fontFamily: "RobotoBlack",
  },
  button: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 50,
    opacity: 0.8,
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 1,
    shadowColor: "#474747",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  buttonLeft: {
    left: 40,
    backgroundColor: colors.white,
    borderColor: colors.main,
  },
  buttonRight: {
    right: 40,
    backgroundColor: "#e198f9",
    borderColor: "#5e006b",
  },
  left: {
    color: "#5e006b",
    fontFamily: "RobotoRegular",
    fontSize: 15,
    textAlign: "center",
  },
  right: {
    color: "#5e006b",
    fontFamily: "RobotoRegular",
    fontSize: 15,
    textAlign: "center",
  },

  centeredView: {
    width: "100%",
    height: "18%",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    marginTop: 125,
    paddingRight: sizes.lg,
  },
  modalView: {
    width: "60%",
    height: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 10,
    shadowColor: colors.black,
    paddingHorizontal: 20,
    paddingVertical: 15,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  userInfo: {
    width: "100%",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 5,
  },
  userAction: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  userName: {
    fontSize: sizes.sm,
    color: colors.main,
    fontFamily: "RobotoRegular",
  },
  userEmail: {
    textAlign: "center",
    fontFamily: "RobotoLight",
    color: "#474747",
  },
  buttonAction: {
    width: 80,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  buttonClose: {
    backgroundColor: "teal",
  },
  buttonSignOut: {
    backgroundColor: "red",
  },
  textStyle: {
    color: "white",
    textAlign: "center",
    fontFamily: "RobotoRegular",
    fontSize: sizes.md / 2,
  },
});
